//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pharmacie1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LABORATOIRE
    {
        public int ID { get; set; }
        public string NAMEL { get; set; }
        public string DESCRIPTIONS { get; set; }
        public string MAIL { get; set; }
        public string PHONE { get; set; }
        public string CITY { get; set; }
        public string CODEPOSTAL { get; set; }
    }
}
